
default_language_version:
    python: python3
exclude: ^docs/(conf.py|_ext/)
default_stages: [commit,push]
fail_fast: false

ci:
    skip: [pylint]
    autoupdate_branch: develop
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
    -   id: poetry-check
        args: [--lock]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        additional_dependencies: [tomli] # to read config from pyproject.toml
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        files: ^(omf/fileio/geoh5|tests/)
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
    -   id: mypy
        files: ^(omf/fileio/geoh5|tests/)
        additional_dependencies: [
#            numpy==1.26.*,  # TODO: fix mypy errors related to numpy
            tomli, # to read config from pyproject.toml
            types-six,
            types-toml,
        ]
        exclude: ^docs/
-   repo: https://github.com/codingjoe/relint
    rev: 3.1.1
    hooks:
    -   id: relint
        args: [-W]  # to fail on warnings
        files: ^omf/fileio/geoh5/
-   repo: http://github.com/MiraGeoscience/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: prepare-commit-msg
    -   id: check-commit-msg
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        require_serial: true  # pylint does its own parallelism
        types: [python]
        files: ^(omf/fileio/geoh5|tests/)
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        exclude: (\.lock|\.ipynb|^THIRD_PARTY_SOFTWARE\.rst)$
        entry: codespell -I .codespellignore
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.mdj$
    -   id: check-json
        exclude_types: [jupyter]
    -   id: check-toml
    -   id: check-yaml
#    -   id: check-added-large-files # crashing on some configuration. To be investigated
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: (^\.idea/.*\.xml|\.mdj)$
    -   id: mixed-line-ending
        exclude: ^\.idea/.*\.xml$
    -   id: name-tests-test
    -   id: pretty-format-json
        args:
            - --autofix
            - --indent=4
            - --no-sort-keys
            - --top-keys
            - version,title,icon,documentation,conda_environment,run_command,geoh5,monitoring_directory,workspace_geoh5
        exclude_types: [jupyter]
        exclude: ^docs/(.*/)?images/
-   repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.4
    hooks:
    -   id: rstcheck
        exclude: ^THIRD_PARTY_SOFTWARE.rst$
        additional_dependencies: [sphinx]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
        exclude: ^THIRD_PARTY_SOFTWARE.rst$
